### ISSUE TITLE
abstürze des adapters

### ISSUE THREAD

**Issue by sjfm-design** [a-i-ks/ioBroker.volumio#12]
**Describe the bug**  
nach adapterstart manchmal kurz grün, danach rot.
![grafik](https://github.com/a-i-ks/ioBroker.volumio/assets/30467409/a78794fc-e0d3-4211-87fe-e2116e6aa790)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![volumio](https://github.com/a-i-ks/ioBroker.volumio/assets/30467409/cebc1b3e-e380-463a-9bd2-f404703331dc)
`<html><body>

 
--
volumio.0 | 2023-11-22 09:01:16.212 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
volumio.0 | 2023-11-22 09:01:16.200 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.200 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:267:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:01:16.200 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.199 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:01:16.198 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.198 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:262:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:01:16.198 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.197 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:01:16.196 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.195 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:260:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:01:16.192 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:01:16.191 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:42.163 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
volumio.0 | 2023-11-22 09:00:42.094 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.093 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:267:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:42.093 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.093 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:42.092 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.092 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:262:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:42.092 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.092 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:42.091 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.090 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:260:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:42.089 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:42.087 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:06.204 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
volumio.0 | 2023-11-22 09:00:06.159 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.159 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:267:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:06.158 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.158 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:06.157 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.157 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:262:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:06.157 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.157 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
volumio.0 | 2023-11-22 09:00:06.156 | error | undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.155 | error | Error:  undefined is not a valid state value     at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)     at Volumio._setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5448:49)     at Volumio.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5409:21)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16     at new Promise (<anonymous>)     at Volumio.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16)     at Volumio.propagatePlayserStateIntoStates  (/opt/iobroker/node_modules/iobroker.volumio/build/main.js:260:14)     at /opt/iobroker/node_modules/iobroker.volumio/build/main.js:254:18     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
volumio.0 | 2023-11-22 09:00:06.154 | error | unhandled promise rejection: undefined is not a valid state value
volumio.0 | 2023-11-22 09:00:06.150 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>`

**Versions:**  
 - Adapter version: v0.1.2
 - JS-Controller version: 5.0.16
 - Node version: v18.18.2
 - Operating system: Debian GNU/Linux 12 (bookworm)

**Additional context**  
gestern noch neueste volumio version frisch auf SDkarte installiert.
![grafik](https://github.com/a-i-ks/ioBroker.volumio/assets/30467409/8be7d344-2820-4271-b792-b05335a848c4)

**Comment by a-i-ks** [comment]
Ich schaue mir das die Tage mal an. Ich muss gestehen, dass ich diesen Adapter schon lange nicht mehr gewartet und weiterentwickelt habe. Mein Hifi Berry auf dem Volumino läuft ist seit einem Umzug vor 2 Jahren nicht mehr in Betrieb. Vielleicht ist das eine gute Gelegenheit, ihn wieder zum Leben zu erwecken, auf die neueste Version von Volumino zu updaten und den Adapter wieder zum Laufen zu bringen. Das wird vielleicht ein paar Tage dauern, aber ich bin dabei!

**Comment by sjfm-design** [comment]
dank erstmal!
mach dir keinen stress. in der stammkneipe laufen 2 volis, die werden über APP gesteuert, falls benötigt. der test voli zu hause ist nur zum spielen und testen da...

**Comment by Xfiles-de** [comment]
Es währe echt genial wenn du es dir augucken würdest ! Bei mir auch schon immer nur noch am abstürzen :(
Danke dir in voraus !

**Comment by a-i-ks** [comment]
Schande über mein Haupt. Ich habe es schon wieder völlig vergessen. So viele Projekte am laufen. Aber ich habe eben Volumio neu installiert und fixe das Ding jetzt in den nächsten Tag. Sorry für die Wartezeit.

**Comment by a-i-ks** [comment]
Kurzes Update: Ich habe den Adapter auf die API Änderungen angepasst. Lokal funktioniert es bei mir. Ich kämpfe noch mit ein paar iobroker Installations Problemen, weil ich die Apdater Struktur auch auf den neuesten Stand angepasst habe und dort irgendwas noch nicht ganz passt. Sobald ich das gelöst habe melde ich mich.

**Comment by a-i-ks** [comment]
So ... der aktuelle master Stand kann jetzt bitte mal getestet werden. Freiwillige vor :)

**Comment by a-i-ks** [comment]
Ich warte jetzt noch bis Samstagabend auf Feedback, dann werde ich den Adapter in v0.2.0 offiziell freigeben. 

Bei mir funktioniert der Adapter jetzt wieder ohne Abstürze. Ich habe ihn jetzt (hoffentlich) fehlersicher umgebaut, so dass er bei eventuellen API-Änderungen und anderen unerwarteten Fehlern nicht mehr abstürzt, sondern nur noch Errors loggt. 

Vom Funktionsumfang hat sich leider nicht viel geändert. Es gibt immer noch sehr viele Funktionen (z.B. Playlist Queue bearbeiten), die noch implementiert werden müssen. Außerdem sagt Volumio selbst auf der Developer Page, dass man eine Websocket basierte API verwenden sollte. 

Ich muss gestehen, dass ich mir nicht sicher bin, ob ich die Zeit für diese Umstellung habe. Der Adapter sollte jetzt mit der vorhandenen Grundfunktionalität stabil laufen. Ich werde weiterhin versuchen, Bugfixes und kleinere Feature-Wünsche umzusetzen. Sobald es aber um Themen wie Multiroom-Geräteverwaltung über Volumio geht, bin ich definitiv raus, da ich kein Premium-Abo habe und auch nicht vorhabe so tief in die Materie einzutauchen. 
Volumio hat eine schicke Oberfläche und erfüllt seinen Zweck ganz gut. Aber auf Codebasis ist es ein absoluter Albtraum. Es macht wirklich keinen Spaß, Erweiterungen dafür zu entwickeln. Ich persönlich bin inzwischen auf Sonos umgestiegen.

**Comment by Xfiles-de** [comment]
Bis jetzt nichts negatives feststellen können ! Vielen dank !

**Comment by a-i-ks** [comment]
Gut dann veröffentliche ich später 0.2.0
