### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [a-i-ks/ioBroker.volumio#16]
Using 'npm run transalte' should fix these:
[W105] Missing suggested translation into pl,uk,zh-cn of "common.titleLang" in io-package.json.
[W109] Missing suggested translation into pl,uk,zh-cn of "common.desc" in io-package.json.
[W145] Missing suggested translation into uk,pl,zh-cn of some "common.news" in io-package.json.

Edit io-package to fix those:
[W170] "common.keywords" should not contain "iobroker, adapter, smart home" io-package.json
[W184] "common.main" is deprecated and ignored. Please remove from io-package.json. Use "main" at package.json instead.
[W184] "common.title" is deprecated and replaced by "common.titleLang". Please remove from io-package.json.

As you do not have 'gulp'listed as dependency, this file is most likely obsolete and can be delted. But please check potential usage!
[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

**Comment by a-i-ks** [comment]
Okay, I'll adjust it right away. But then this should also be done in the adapter template.
