### ISSUE TITLE
Consider updateing js.controller / admin dependencies

### ISSUE THREAD

**Issue by mcm1957** [a-i-ks/ioBroker.volumio#17]
Current dependencies at io-package.jsosn seem to be outdated:
```
        "dependencies": [
            {
                "js-controller": ">=3.3.22"
            }
        ],
        "globalDependencies": [
            {
                "admin": ">=5.1.13"
            }
        ]
```

js-controller should be at least 4.0.24. 5.0.19 would be reommended for new (or almost new / renewed) adapters.
admin should be 6.13.16 as admin has several fixes for jsonConfig implemented at 6.x.x. So for new adapters 6.13.16 is recommended.

Please evalute / consider upgrading dependencies.

**Comment by a-i-ks** [comment]
Okay, I'll adjust it right away. But then this should also be done in the adapter template. 
See https://github.com/ioBroker/ioBroker.example/pull/106
