### ISSUE TITLE
Please reevaluate / correct state roles

### ISSUE THREAD

**Issue by mcm1957** [a-i-ks/ioBroker.volumio#18]
Please reevaluate state roles

  Only the values specified here (https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md) may be used as state roles. Do not invent new names as this might disturb the functionalyity of other adapters or vis.

  In addition the roles MUST match the read/write functionality. As an example a role value.* requires that the state is a readable state. Input states (write only) should have roles like level.*. Please read the description carefully. States with role 'button' should (must) have attribute 'common.read=false' set. A button ( "Taster" in german only triggers when you press but else has no state), so it should also be not readable. This is also like HomeMatic does it. A switch has clear states true or false and so can be read.

  Please avoid using general roles (state, value) whnever a dedicated role exists.

Some examples of to be fixed roles - list is NOT complete, please check all state definitions:

- https://github.com/a-i-ks/ioBroker.volumio/blob/b4302423f93f67990d1905c505b05f87dd66e268/io-package.json#L302
writeable state miust not have role 'value'. If no better matching role is available role 'level' must be used.

- roles player.* do not exist and must not be used. Please see docu for existing replacements

**Comment by a-i-ks** [comment]
Thanks for the clarification. Should be fixed now.

**Comment by mcm1957** [comment]
Just for Info:
State Roles are used by (some) vis Adapters to decide which functionality to display / use. So its always a good idea to have correct roles. If you are missing some please feel free to contact us (i.e. telegram dev channel) an provide an extension PR. We can discuss / decide this rutehr fast latests at next dev. meeting in most cases.
