### ISSUE TITLE
Subscription will not update when volumio was restarted

### ISSUE THREAD

**Issue by Leviathan09** [a-i-ks/ioBroker.volumio#3]
Hi @a-i-ks  found another little bug for the subscription ;-)

When the adapter is running and i restart Volumio the objects will not be updated after the restart.
If have to restart the adapter to get updates again this.

Maybe a kind of timeout can be build in so the adapter stops itself after XX seconds
or
a automatic restart of the adapter after it reconnects to volumio (which leads me to issue #4 )

**Comment by a-i-ks** [comment]
Ah okay, good that you pointed out this behaviour to me. I was not aware until now that the notification targets in Volumio do not survive a restart. This means that in subscription mode I have to regularly check whether Volumio is still online and whether the adapter is still registered as a notification target. 
Argh, that is a very unattractive solution from Volumio. I have noticed more often now that the code quality of Volumio is rather suboptimal in some places.

**Comment by a-i-ks** [comment]
Connection check interval is now implemented.

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
