### ISSUE TITLE
Nice :-) but how to install correctly?

### ISSUE THREAD

**Issue by gregor-hh** [a-i-ks/ioBroker.volumio#6]
Thank you very much for this plugin, I want test it but how to install it?

I have run npm install iobroker.volumio but i dont see the instance?

(It is the first time that I installed a plugin manually.

any hints?

EDIT: Ahhh, I have found, had to go in /opt/iobroker/ and after npm install manually add the instance with the + , sry :-)

best regards

**Comment by a-i-ks** [comment]
There is another easier way: If you go to the adapter view in ioBroker, there is a button "labeled: install from own URL" (it has a GitHub icon) and enter this URL on the "other"-Tab:
https://github.com/b.com/a-i-ks/ioBroker.volumio/tarball/master/
You can always use this method to install the latest development state of an adapter from GitHub. But this may install a work-in-progress version. I hope that the adapter will be added to the official repository in the next few days. Then it can also be installed normally.
